<?php

return [
    'klien' => [
        'no_ktp'        => ['index'=>true,'type'=>'string'],
        'nama'          => ['index'=>true,'type'=>'string'],
        'tgl_lahir'     => ['index'=>false,'type'=>'date'],
        'tempat_lahir'  => ['index'=>false,'type'=>'string'],
        'alamat'        => ['index'=>true,'type'=>'text'],
        'rt'            => ['index'=>false,'type'=>'integer'],
        'rw'            => ['index'=>false,'type'=>'integer'],
        'desa'          => ['index'=>false,'type'=>'string'],
        'kecamatan'     => ['index'=>false,'type'=>'string'],
        'kabupaten'     => ['index'=>false,'type'=>'string'],
        'provinsi'      => ['index'=>false,'type'=>'string'],
        'kodepos'       => ['index'=>false,'type'=>'integer'],
        'warga_negara'  => ['index'=>false,'type'=>'string'],
        'status_pernikahan' => ['index'=>false,'type'=>'string'],
        'pekerjaan'     => ['index'=>false,'type'=>'string'],
        'agama'         => ['index'=>false,'type'=>'string'],
        'telpon'        => ['index'=>false,'type'=>'string'],
        'handphone'     => ['index'=>false,'type'=>'string'],
        'npwp'          => ['index'=>false,'type'=>'string'],
    ],
    'jadwal' => [ 
        'waktu'         => ['index'=>true,'type'=>'datetime'],
        'keterangan'    => ['index'=>true,'type'=>'text'],
        'klien_id'      => ['index'=>'nama','type'=>'id'],
    ],
    'sk' => [
        'saksi'         => ['index'=>false,'type'=>'string'],
        'keterangan'    => ['index'=>true,'type'=>'text'],
        'klien_id'      => ['index'=>'nama','type'=>'id'],
        'user_id'       => ['index'=>'name','type'=>'id'],
    ],
    'transaksi' => [
        'waktu'         => ['index'=>true,'type'=>'datetime'],
        'lampiran'      => ['index'=>false,'type'=>'string'],
        'jenis'         => ['index'=>true,'type'=>'string'],
        'keterangan'    => ['index'=>true,'type'=>'text'],
        'nominal'       => ['index'=>true,'type'=>'bigInteger'],
        'sk_id'         => ['index'=>'keterangan','type'=>'id'],
    ],
    'retribusi' => [
        'waktu'         => ['index'=>true,'type'=>'datetime'],
        'lampiran'      => ['index'=>false,'type'=>'string'],
        'jenis'         => ['index'=>true,'type'=>'string'],
        'keterangan'    => ['index'=>true,'type'=>'text'],
        'nominal'       => ['index'=>true,'type'=>'bigInteger'],
        'sk_id'         => ['index'=>'keterangan','type'=>'id'],
    ],
    'legal' => [
        'waktu'         => ['index'=>true,'type'=>'datetime'],
        'sifat_surat'   => ['index'=>true,'type'=>'string'],
        'keterangan'    => ['index'=>true,'type'=>'text'],
        'sk_id'         => ['index'=>'keterangan','type'=>'id'],
    ],
    'warmerken' => [
        'waktu'         => ['index'=>true,'type'=>'datetime'],
        'sifat_surat'   => ['index'=>true,'type'=>'string'],
        'keterangan'    => ['index'=>true,'type'=>'text'],
        'sk_id'         => ['index'=>'keterangan','type'=>'id'],
    ],
    'notariil' => [
        'waktu'         => ['index'=>true,'type'=>'datetime'],
        'no_akta'       => ['index'=>true,'type'=>'string'],
        'nama_akta'     => ['index'=>true,'type'=>'string'],
        'keterangan'    => ['index'=>true,'type'=>'text'],
        'sk_id'         => ['index'=>'keterangan','type'=>'id'],
    ],
    'ppat' => [
        'waktu'         => ['index'=>true,'type'=>'date'],
        'waktu_ssp'     => ['index'=>true,'type'=>'date'],
        'waktu_bphtb'   => ['index'=>true,'type'=>'date'],
        'ssp'           => ['index'=>false,'type'=>'text'],
        'bphtb'         => ['index'=>false,'type'=>'text'],
        'ht'            => ['index'=>false,'type'=>'integer'],
        'keterangan'    => ['index'=>false,'type'=>'text'],
        'sk_id'         => ['index'=>'keterangan','type'=>'id'],
        'properti_id'   => ['index'=>'pemeganghak','as'=>'pemegang_hak','type'=>'id'],
    ],
    'properti' => [
        'waktu_su'      => ['index'=>true,'type'=>'date'],
        'nomor_hm'      => ['index'=>true,'type'=>'integer'],
        'nib'           => ['index'=>true,'type'=>'string'],
        'nomor_ssp'     => ['index'=>true,'type'=>'integer'],
        'luastanah'     => ['index'=>false,'type'=>'decimal'],
        'luasbangunan'  => ['index'=>false,'type'=>'decimal'],
        'letak'         => ['index'=>false,'type'=>'text'],
        'nop'           => ['index'=>true,'type'=>'string'],
        'njop'          => ['index'=>true,'type'=>'string'],
        'pemeganghak'   => ['index'=>true,'type'=>'string'],
        'jenis'         => ['index'=>false,'type'=>'string'],
    ],
    'jadwal_sk' => [
        'sk_id'         => ['index'=>'keterangan','type'=>'id'],
        'jadwal_id'     => ['index'=>'waktu','type'=>'id'],
        'hasil'         => ['index'=>false,'type'=>'text'],
    ],
];